DROP TABLE IF EXISTS `projeto-tembici-487111.GOLD.BD_TEMBICI`;

CREATE OR REPLACE TABLE `projeto-tembici-487111.GOLD.BD_TEMBICI`
CLUSTER BY PROJETO, CLIENTE, ID_CLIENTE
OPTIONS(
  description='Tabela analítica consolidada - Tembici'
)

AS
WITH

-- =====================================================
-- 1) BASE DE VIAGENS
-- =====================================================
VIAGENS AS (
  SELECT
    PROJECT AS PROJETO,
    CUSTOMER AS CLIENTE,
    TRIP AS ID_VIAGEM,
    START_TIME AS INICIO_VIAGEM_TS,
    END_TIME AS FIM_VIAGEM_TS,
    CAST(DURATION_SECONDS AS INT64) AS DURACAO_SEGUNDOS,
    INVOICE_ID AS ID_FATURA,
    INVOICE_LINE_ID AS ID_LINHA_FATURA,
    DATE(START_TIME) AS DATA_VIAGEM,
    CASE
        WHEN END_TIME IS NULL THEN 'SEM_FIM'
        ELSE 'FINALIZADA'
    END AS STATUS_VIAGEM
  FROM `projeto-tembici-487111.BRONZE.VIAGENS`
  WHERE START_TIME IS NOT NULL
),

-- =====================================================
-- 2) FATURAS
-- =====================================================
FATURAS AS (
  SELECT
    PROJECT AS PROJETO,
    INVOICE_ID AS ID_FATURA,
    INVOICE_LINE_ID AS ID_LINHA_FATURA,
    INVOICE_STATUS AS STATUS_FATURA,
    CAST(USAGE_FEE AS FLOAT64) AS VLR_MULTA
  FROM `projeto-tembici-487111.BRONZE.FATURAS`
),

-- =====================================================
-- 3) CLIENTES / ASSINATURAS
-- =====================================================
CLIENTES AS (
  SELECT
    PROJECT AS PROJETO,
    CUSTOMER AS CLIENTE,
    USER_ID AS ID_CLIENTE,
    PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%E*S UTC', SUBSCRIPTION_START_DATE) AS INICIO_ASSINATURA_TS,
    PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%E*S UTC', SUBSCRIPTION_END_DATE) AS FIM_ASSINATURA_TS,
    CASE
        WHEN UPPER (TRIM(PLAN_TYPE)) IS NULL THEN 'SEM PLANO'
        WHEN UPPER (TRIM(PLAN_TYPE)) = 'SHORT' THEN 'CURTO'
        WHEN UPPER (TRIM(PLAN_TYPE)) = 'LONG' THEN 'LONGO'
    END AS TIPO_PLANO,
    CASE
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = '1 HOUR' THEN '1 HORA'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = '3 DAYS' THEN '3 DIAS'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'DAILY' THEN 'DIÁRIO'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'DAY' THEN '1 DIA'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'MONTHLY' THEN 'MENSAL'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'MONTH' THEN '1 MÊS'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'QUARTERLY' THEN 'TRIMESTRAL'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'SEMIANNUALLY' THEN 'SEMESTRAL'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'TRIP' THEN 'VIAGEM'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'WEEKLY' THEN 'SEMANAL'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'YEARLY' THEN 'ANUAL'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'YEAR' THEN '1 ANO'
        WHEN UPPER(TRIM(PLAN_PERIODICITY)) = 'OTHERS' THEN 'OUTROS'
        WHEN PLAN_PERIODICITY IS NULL THEN 'SEM PLANO'
        ELSE 'OUTROS'
    END AS PERIODICIDADE_PLANO,
    CAST(PLAN_COST AS FLOAT64) AS CUSTO_PLANO,
    CAST(IS_CUSTOMER_FIRST_PURCHASE AS BOOL) AS PRIMEIRA_COMPRA,
    CAST(IS_CUSTOMER_RETURNING AS BOOL) AS CLIENTE_RECORRENTE,
    PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%E*S UTC', DATE_JOINED) AS DATA_CADASTRO_TS
  FROM `projeto-tembici-487111.BRONZE.CLIENTES`
  WHERE USER_ID IS NOT NULL
),

-- =====================================================
-- 4) ERROS UNLOCK (DEDUPLICADO)
-- =====================================================
ERROS_UNLOCK_DEDUP AS (
  SELECT
    PROJECT AS PROJETO,
    USER_ID AS ID_CLIENTE,
    EVENT_TIMESTAMP AS DATA_EVENTO_TS,
    DATE(EVENT_TIMESTAMP) AS DATA_EVENTO,
    EVENT_NAME AS NOME_EVENTO,
    ERROR_TYPE AS TIPO_ERRO
  FROM (
    SELECT
      *,
      ROW_NUMBER() OVER (
        PARTITION BY PROJECT, USER_ID, EVENT_TIMESTAMP, EVENT_NAME, IFNULL(ERROR_TYPE,'')
        ORDER BY EVENT_TIMESTAMP
      ) AS RN
    FROM `projeto-tembici-487111.BRONZE.UNLOCK_ERROS`
  )
  WHERE RN = 1
),

-- =====================================================
-- 5) CONTAGEM TOTAL DE ERROS POR CLIENTE
-- =====================================================
ERROS_TOTAL_POR_CLIENTE AS (
  SELECT
    PROJETO,
    ID_CLIENTE,
    COUNT(*) AS QTD_TOTAL_ERROS_CLIENTE
  FROM ERROS_UNLOCK_DEDUP
  GROUP BY 1, 2
),

-- =====================================================
-- 6) ASSINATURA VIGENTE NA DATA DA VIAGEM
-- =====================================================
VIAGENS_COM_ASSINATURA AS (
  SELECT
    V.*,
    C.ID_CLIENTE,
    C.TIPO_PLANO,
    C.PERIODICIDADE_PLANO,
    C.CUSTO_PLANO,
    C.PRIMEIRA_COMPRA,
    C.CLIENTE_RECORRENTE,
    C.INICIO_ASSINATURA_TS,
    C.FIM_ASSINATURA_TS,
    C.DATA_CADASTRO_TS,
    ROW_NUMBER() OVER (
    PARTITION BY V.PROJETO, V.ID_VIAGEM
    ORDER BY C.INICIO_ASSINATURA_TS DESC NULLS LAST
    ) AS RN_ASSINATURA
  FROM VIAGENS V
  LEFT JOIN CLIENTES C
    ON V.PROJETO = C.PROJETO
   AND V.CLIENTE = C.CLIENTE
   AND V.INICIO_VIAGEM_TS >= C.INICIO_ASSINATURA_TS
   AND (C.FIM_ASSINATURA_TS IS NULL OR V.INICIO_VIAGEM_TS < C.FIM_ASSINATURA_TS)
),

-- =====================================================
-- 7) ERROS NA MESMA DATA DA VIAGEM
-- =====================================================
ERROS_NA_DATA_VIAGEM AS (
  SELECT
    VCA.PROJETO,
    VCA.ID_VIAGEM,
    STRING_AGG(DISTINCT REGEXP_EXTRACT(EU.TIPO_ERRO, r'/([^/]+)$'), ', ' 
  ORDER BY REGEXP_EXTRACT(EU.TIPO_ERRO, r'/([^/]+)$')) AS TIPOS_ERRO_NA_DATA
  FROM VIAGENS_COM_ASSINATURA VCA
  INNER JOIN ERROS_UNLOCK_DEDUP EU
    ON VCA.PROJETO = EU.PROJETO
   AND VCA.ID_CLIENTE = EU.ID_CLIENTE
   AND VCA.DATA_VIAGEM = EU.DATA_EVENTO
  WHERE VCA.RN_ASSINATURA = 1
  GROUP BY 1, 2
)

-- =====================================================
-- SELECT FINAL - TABELA CONSOLIDADA
-- =====================================================
SELECT
  -- ============ CHAVES ============
  VCA.PROJETO,
  VCA.STATUS_VIAGEM,
  VCA.ID_VIAGEM,
  CONCAT(VCA.PROJETO, '|', CAST(VCA.ID_VIAGEM AS STRING)) AS CHAVE_VIAGEM,
  VCA.CLIENTE,
  VCA.ID_CLIENTE,
  VCA.DATA_CADASTRO_TS AS DATA_CADASTRO,
  CASE 
    WHEN VCA.CLIENTE_RECORRENTE IS TRUE THEN 'RECORRENTE'
    ELSE 'NÃO RECORRENTE'
  END AS EH_CLIENTE_RECORRENTE,
  CASE 
    WHEN VCA.PRIMEIRA_COMPRA IS TRUE THEN 'SIM'
    ELSE 'NÃO'
  END AS EH_PRIMEIRA_COMPRA,

  -- ============ DIMENSÕES TEMPORAIS ============
  VCA.INICIO_VIAGEM_TS AS HORARIO_INICIO_VIAGEM,
  VCA.FIM_VIAGEM_TS AS HORARIO_FIM_VIAGEM,
  VCA.DATA_VIAGEM,
  
  EXTRACT(YEAR FROM VCA.DATA_VIAGEM) AS ANO,
  ['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ']
  [ORDINAL(EXTRACT(MONTH FROM VCA.DATA_VIAGEM))] AS MES,
  EXTRACT(DAY FROM VCA.DATA_VIAGEM) AS DIA,
  EXTRACT(HOUR FROM VCA.INICIO_VIAGEM_TS) AS HORA_INICIO,
  
  CASE 
    WHEN EXTRACT(DAYOFWEEK FROM VCA.DATA_VIAGEM) IN (1, 7) THEN 'FIM DE SEMANA'
    ELSE 'DIA ÚTIL'
  END AS TIPO_DIA_SEMANA,
  
  CASE
    WHEN EXTRACT(HOUR FROM VCA.INICIO_VIAGEM_TS) BETWEEN 6 AND 9 THEN 'PICO MANHÃ'
    WHEN EXTRACT(HOUR FROM VCA.INICIO_VIAGEM_TS) BETWEEN 17 AND 20 THEN 'PICO TARDE'
    WHEN EXTRACT(HOUR FROM VCA.INICIO_VIAGEM_TS) BETWEEN 10 AND 16 THEN 'HORÁRIO COMERCIAL'
    ELSE 'FORA DE PICO'
  END AS PERIODO_DIA,

  -- ============ MÉTRICAS DE DURAÇÃO ============
  CONCAT(CAST(DIV(VCA.DURACAO_SEGUNDOS, 3600) AS STRING),':',LPAD(CAST(DIV(MOD(VCA.DURACAO_SEGUNDOS, 3600), 60) AS STRING),2,'0'),'h') AS DURACAO_VIAGEM,
  ROUND(VCA.DURACAO_SEGUNDOS / 3600.0, 2) AS DURACAO_HORAS,
  CASE 
    WHEN VCA.DURACAO_SEGUNDOS <= 900 THEN 'ATÉ 15 MIN'
    WHEN VCA.DURACAO_SEGUNDOS <= 3600 THEN 'ATÉ 1H'
    WHEN VCA.DURACAO_SEGUNDOS <= 7200 THEN 'ATÉ 2H'
    WHEN VCA.DURACAO_SEGUNDOS > 7200 THEN 'MAIS DE 2H'
  END AS GRUPO_DURACAO_VIAGEM,

  -- ============ MULTAS ============
  CASE WHEN VCA.ID_FATURA IS NOT NULL THEN 'SIM' ELSE 'NÃO' END AS POSSUI_FATURA,
  CASE 
    WHEN UPPER(TRIM(F.STATUS_FATURA)) NOT IN ('CANCEL','CANCELLED') AND F.VLR_MULTA IS NOT NULL THEN 'SIM' 
    ELSE 'NÃO' 
  END AS POSSUI_MULTA,
  VCA.ID_FATURA,
  VCA.ID_LINHA_FATURA,
  COALESCE(F.VLR_MULTA, 0) AS VLR_MULTA,
  CASE
    WHEN UPPER(TRIM(F.STATUS_FATURA)) IN ('CANCEL', 'CANCELLED') THEN 'CANCELADA'
    WHEN UPPER(TRIM(F.STATUS_FATURA)) IN ('PAID', 'PAID_NO_CC') THEN 'PAGO'
    WHEN UPPER(TRIM(F.STATUS_FATURA)) = 'HOLD_PAID' THEN 'PAGAMENTO RETIDO'
    WHEN UPPER(TRIM(F.STATUS_FATURA)) IN ('UNPAID') THEN 'EM ABERTO'
    ELSE NULL
  END AS STATUS_PGTO_MULTA,

  -- ============ ASSINATURA ============
  CASE 
    WHEN VCA.TIPO_PLANO IS NULL THEN 'SEM PLANO'
    ELSE VCA.TIPO_PLANO
  END AS TIPO_PLANO,
  CASE 
    WHEN VCA.PERIODICIDADE_PLANO IS NULL THEN 'SEM PLANO'
    ELSE VCA.PERIODICIDADE_PLANO
  END AS PERIODICIDADE_PLANO,  
  COALESCE(VCA.CUSTO_PLANO, 0) AS CUSTO_PLANO,
  VCA.INICIO_ASSINATURA_TS AS DATA_INICIO_ASSINATURA,
  VCA.FIM_ASSINATURA_TS AS DATA_FIM_ASSINATURA,
  CASE 
    WHEN INICIO_ASSINATURA_TS IS NULL THEN 'SEM ASSINATURA'
    WHEN FIM_ASSINATURA_TS IS NULL THEN 'ATIVA'
    WHEN FIM_ASSINATURA_TS <= CURRENT_TIMESTAMP() THEN 'ENCERRADA'
    ELSE 'ATIVA'
  END AS STATUS_ASSINATURA_ATUAL,
  CASE
    WHEN INICIO_ASSINATURA_TS IS NULL THEN 'SEM ASSINATURA'
    WHEN FIM_ASSINATURA_TS IS NULL THEN 'ATIVA NA VIAGEM'
    WHEN INICIO_VIAGEM_TS < FIM_ASSINATURA_TS THEN 'ATIVA NA VIAGEM'
    ELSE 'ENCERRADA NA VIAGEM'
  END AS STATUS_ASSINATURA_VIAGEM,

  -- ============ INDICADORES - ERROS ============
  COALESCE(ETC.QTD_TOTAL_ERROS_CLIENTE, 0) AS QTD_TOTAL_ERROS_CLIENTE,
  EDV.TIPOS_ERRO_NA_DATA AS TIPOS_ERRO_NA_DATA_VIAGEM,
  CASE 
    WHEN EDV.TIPOS_ERRO_NA_DATA IS NOT NULL THEN 'SIM'
    ELSE 'NÃO'
  END AS TEVE_ERRO_NA_DATA_VIAGEM

FROM VIAGENS_COM_ASSINATURA VCA
LEFT JOIN FATURAS F
  ON VCA.PROJETO = F.PROJETO
 AND VCA.ID_FATURA = F.ID_FATURA
 AND VCA.ID_LINHA_FATURA = F.ID_LINHA_FATURA
LEFT JOIN ERROS_TOTAL_POR_CLIENTE ETC
  ON VCA.PROJETO = ETC.PROJETO
 AND VCA.ID_CLIENTE = ETC.ID_CLIENTE
LEFT JOIN ERROS_NA_DATA_VIAGEM EDV
  ON VCA.PROJETO = EDV.PROJETO
 AND VCA.ID_VIAGEM = EDV.ID_VIAGEM
WHERE VCA.RN_ASSINATURA = 1
;